### ISSUE TITLE
Cannot use prototype as @process

### ISSUE THREAD

**Issue by kdambekalns** [neos/fusion-afx#7]
All of these do not work:

```
// -> literally "Acme.Com:Processor" as result
<a href={props.href} @process.foo="Acme.Com:Processor">

// -> Expression "Acme.Com:Processor" could not be parsed. Error starting at character 18: ":Processor".
<a href={props.href} @process.foo={Acme.Com:Processor}>

// -> Prop-assignment "@process.foo" was not followed by quotes or braces
<a href={props.href} @process.foo=Acme.Com:Processor>
```

But this would work in "pure" Fusion:

    @process.tracking = Acme.Com:Processor

**Comment by Sebobo** [comment]
You can do 
```
<a href={props.href}>
  <Acme.Com:Processor @path="process.foo"/>
```

**Comment by mficzel** [comment]
@kdambekalns @Sebobo How about a syntax like this:
```
<a href={props.href} @process.foo=<Acme.Com:Processor/> >
```
This would allow to separate afx-attributes from expression and string attributes.

**Comment by Sebobo** [comment]
Personally I dislike the tag/prototype in an attribute style. JSX also doesn't allow it I think. 

Just found out some days ago that XSL also does it the same way as AFX does it now. Have a child tag and apply its result to an attribute of the parent.

**Comment by mficzel** [comment]
JSX would allow you to do this <a href={props.href} @process.foo={<Acme.Com:Processor/>} >

**Comment by Sebobo** [comment]
`<a href={props.href} @process.foo={<Acme.Com:Processor/>} >` looks a bit better than the other proposals IMO.

**Comment by mhsdesign** [comment]
it could maybe be solved with `<a href={props.href} @process.foo={afx:<Acme.Com:Processor/>} >...</a>` as @mficzel pointed out in [slack](https://neos-project.slack.com/archives/C04PYL8H3/p1636890665008200)

**Comment by Sebobo** [comment]
Still don't like how the code looks when tags are contained in attributes.

**Comment by mficzel** [comment]
@Sebobo JSX allows jsx in attributes like this:

```
<Foo stuff={<Bar />} />
```

In this regard it would make sense to allow an expression to contain afx again maybe like this:

```
afx`<Foo stuff={afx:<Bar />} />`
```

**Comment by mhsdesign** [comment]
could be solved by my afx in eel approach similar to jsx: https://github.com/neos/fusion-afx/issues/28#issuecomment-1012425673
what do you think?
